spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/${spring.datasource.name}
    driver-class-name: org.mariadb.jdbc.Driver
    password: sms
    username: sms
    name: labschoolbd
  liquibase:
    enabled: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    clean-disabled: false
    clean-on-validation-error: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${spring.datasource.name}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
  profiles:
    active: local

server:
  error:
    include-stacktrace: on_param
